# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_required', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='req_item',
        ),
        migrations.AddField(
            model_name='itemrequirement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='req_item',
            field=models.ManyToManyField(through='inventory.ItemRequirement', to='inventory.Item'),
        ),
    ]
